name: Build

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3.1.3
      with:
        name: DiscordIPC
        path: target/*.jar
